services:
  - type: web
    name: maraphoto-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
